# Generated by Django 5.2.18 on 2026-10-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bottom_size',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_style',
            field=models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('eastern', 'Eastern'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shoe_size',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_size',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
