# Generated by Django 5.2.18 on 2026-10-08 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bottom_size_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monk_tone',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='undertone',
            field=models.CharField(blank=True, choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral')], max_length=10, null=True),
        ),
    ]
