# Generated by Django 5.2.18 on 2026-10-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_monk_tone_userprofile_undertone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avoided_colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_colors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
