# Generated by Django 5.2.18 on 2026-10-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_avoided_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='body_preset',
            field=models.CharField(choices=[('slim', 'Slim (waist 30-32)'), ('regular', 'Regular (waist 34-38)'), ('plus', 'Plus (waist 40+)')], default='regular', max_length=10),
        ),
    ]
