# Generated by Django 5.2.18 on 2026-10-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_body_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cultural_preference',
            field=models.CharField(default='Western', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_style',
            field=models.CharField(default='mixed', max_length=50),
        ),
    ]
