# Generated by Django 5.2.18 on 2026-10-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Men Shirt', 'Men Shirt'), ('Men Pant', 'Men Pant'), ('Men Shoes', 'Men Shoes'), ('Men Cap', 'Men Cap'), ('Men Shalwar Kameez', 'Men Shalwar Kameez'), ('Men Sandals', 'Men Sandals'), ('Women Kurta', 'Women Kurta'), ('Women Shalwar Kameez', 'Women Shalwar Kameez'), ('Women Footwear', 'Women Footwear'), ('Women Pant', 'Women Pant'), ('Women Shirt', 'Women Shirt')], max_length=100)),
                ('cultural_tag', models.CharField(choices=[('Eastern', 'Eastern'), ('Western', 'Western'), ('Casual', 'Casual'), ('Formal', 'Formal')], max_length=100)),
                ('compatible_skin_tone', models.CharField(choices=[('Fair', 'Fair'), ('Medium', 'Medium'), ('Dark', 'Dark'), ('All', 'All')], max_length=50)),
                ('color', models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Navy Blue', 'Navy Blue'), ('Beige', 'Beige'), ('Grey', 'Grey'), ('Charcoal Grey', 'Charcoal Grey'), ('Tan', 'Tan'), ('Brown', 'Brown'), ('Dark Brown', 'Dark Brown'), ('Sky Blue', 'Sky Blue'), ('Royal Blue', 'Royal Blue'), ('Maroon', 'Maroon'), ('Wine Red', 'Wine Red'), ('Emerald Green', 'Emerald Green'), ('Deep Purple', 'Deep Purple'), ('Bottle Green', 'Bottle Green'), ('Burgundy', 'Burgundy'), ('Pastel Pink', 'Pastel Pink'), ('Soft Lavender', 'Soft Lavender'), ('Light Grey', 'Light Grey'), ('Denim Blue', 'Denim Blue'), ('Mustard Yellow', 'Mustard Yellow'), ('Olive Green', 'Olive Green'), ('Rust Orange', 'Rust Orange'), ('Teal', 'Teal'), ('Coral', 'Coral'), ('Camel', 'Camel'), ('Off-White', 'Off-White'), ('Peach', 'Peach'), ('Turquoise', 'Turquoise'), ('Khaki', 'Khaki'), ('Light Olive', 'Light Olive'), ('Deep Teal', 'Deep Teal'), ('Bright Yellow', 'Bright Yellow'), ('Fuchsia Pink', 'Fuchsia Pink'), ('Orange', 'Orange'), ('Bright Red', 'Bright Red'), ('Cobalt Blue', 'Cobalt Blue'), ('Yellow', 'Yellow'), ('Fuchsia', 'Fuchsia'), ('Bright Orange', 'Bright Orange'), ('Hot Pink', 'Hot Pink'), ('Lemon Yellow', 'Lemon Yellow'), ('Cream', 'Cream'), ('Charcoal', 'Charcoal')], max_length=50, null=True)),
                ('garment_type', models.CharField(blank=True, choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Footwear', 'Footwear'), ('Accessory', 'Accessory')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('size_s_stock', models.PositiveIntegerField(default=0)),
                ('size_m_stock', models.PositiveIntegerField(default=0)),
                ('size_l_stock', models.PositiveIntegerField(default=0)),
                ('size_xl_stock', models.PositiveIntegerField(default=0)),
                ('size_xxl_stock', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Out of Stock', 'Out of Stock')], default='Active', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
