# Generated by Django 5.2.18 on 2026-10-08 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use a hex colour such as #1a2b3c.')]),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_palette',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='formality',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slot',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('bottom', 'Bottom'), ('kurta', 'Kurta / kameez'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('dupatta', 'Dupatta')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='style_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men Shirt', 'Men Shirt'), ('Men Pant', 'Men Pant'), ('Men Shoes', 'Men Shoes'), ('Men Cap', 'Men Cap'), ('Men Shalwar Kameez', 'Men Shalwar Kameez'), ('Men Sandals', 'Men Sandals'), ('Women Kurta', 'Women Kurta'), ('Women Shalwar Kameez', 'Women Shalwar Kameez'), ('Women Footwear', 'Women Footwear'), ('Women Pant', 'Women Pant'), ('Women Shirt', 'Women Shirt'), ('Men Outerwear', 'Men Outerwear'), ('Women Outerwear', 'Women Outerwear'), ('Unisex Outerwear', 'Unisex Outerwear'), ('Men Accessory', 'Men Accessory'), ('Women Accessory', 'Women Accessory'), ('Unisex Accessory', 'Unisex Accessory'), ('Unisex Shirt', 'Unisex Shirt'), ('Unisex Pant', 'Unisex Pant'), ('Unisex Shoes', 'Unisex Shoes'), ('Women Dupatta', 'Women Dupatta')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Out of Stock', 'Out of Stock'), ('Draft', 'Draft')], default='Active', max_length=50),
        ),
    ]
