# Generated by Django 5.2.18 on 2026-10-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_catalog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/back/'),
        ),
        migrations.AddField(
            model_name='product',
            name='mannequin_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/mannequin/'),
        ),
        migrations.AddField(
            model_name='product',
            name='mannequin_note',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='mannequin_ready',
            field=models.BooleanField(default=False),
        ),
    ]
