# Generated by Django 5.2.18 on 2026-10-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToneColorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depth', models.CharField(choices=[('Fair', 'Fair'), ('Medium', 'Medium'), ('Dark', 'Dark')], max_length=10)),
                ('undertone', models.CharField(choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral')], max_length=10)),
                ('color_name', models.CharField(max_length=60)),
                ('score', models.SmallIntegerField(choices=[(2, 'Best'), (1, 'Good'), (-2, 'Avoid')])),
            ],
            options={
                'ordering': ['depth', 'undertone', '-score', 'color_name'],
                'constraints': [models.UniqueConstraint(fields=('depth', 'undertone', 'color_name'), name='unique_tone_color_rule')],
            },
        ),
    ]
