# Generated by Django 5.2.18 on 2026-10-07 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('detected_skin_tone', models.CharField(choices=[('Fair', 'Fair'), ('Medium', 'Medium'), ('Dark', 'Dark'), ('Rescan Required', 'Rescan Required'), ('Unknown', 'Unknown')], max_length=50)),
                ('confidence_score', models.FloatField(default=0)),
                ('lighting_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('brightness', models.FloatField(default=0)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
