# Generated by Django 5.2.18 on 2026-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facescanrecord',
            name='hue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facescanrecord',
            name='ita',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facescanrecord',
            name='monk',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facescanrecord',
            name='undertone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
