# Generated by Django 6.0.6 on 2026-07-07 18:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Out of Stock', 'Out of Stock')], default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Jacket', 'Jacket'), ('Cap', 'Cap'), ('Shoes', 'Shoes'), ('Tie', 'Tie'), ('Coat', 'Coat'), ('Shalwar Kameez', 'Shalwar Kameez'), ('Waistcoat', 'Waistcoat'), ('Sandals', 'Sandals'), ('Chappals', 'Chappals'), ('Watch', 'Watch'), ('Accessory', 'Accessory')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='compatible_skin_tone',
            field=models.CharField(choices=[('Fair', 'Fair'), ('Medium', 'Medium'), ('Dark', 'Dark')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='cultural_tag',
            field=models.CharField(choices=[('Eastern', 'Eastern'), ('Western', 'Western'), ('Formal', 'Formal'), ('Casual', 'Casual')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cultural_preference',
            field=models.CharField(choices=[('Eastern', 'Eastern'), ('Western', 'Western'), ('Formal', 'Formal'), ('Casual', 'Casual')], default='Western', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_tone',
            field=models.CharField(blank=True, choices=[('Fair', 'Fair'), ('Medium', 'Medium'), ('Dark', 'Dark')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('booking_type', models.CharField(choices=[('Virtual Mannequin Preview', 'Virtual Mannequin Preview'), ('Styling Consultation', 'Styling Consultation'), ('Outfit Trial Request', 'Outfit Trial Request')], max_length=100)),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='FaceScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('detected_skin_tone', models.CharField(choices=[('Fair', 'Fair'), ('Medium', 'Medium'), ('Dark', 'Dark'), ('Rescan Required', 'Rescan Required'), ('Unknown', 'Unknown')], max_length=50)),
                ('confidence_score', models.FloatField(default=0)),
                ('lighting_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('brightness', models.FloatField(default=0)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.product')),
            ],
        ),
    ]
