# Generated by Django 6.0.6 on 2026-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_cost_price_product_created_at_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men Shirt', 'Men Shirt'), ('Men Pant', 'Men Pant'), ('Men Shoes', 'Men Shoes'), ('Men Cap', 'Men Cap'), ('Men Shalwar Kameez', 'Men Shalwar Kameez'), ('Men Sandals', 'Men Sandals'), ('Women Kurta', 'Women Kurta'), ('Women Shalwar Kameez', 'Women Shalwar Kameez'), ('Women Footwear', 'Women Footwear'), ('Women Pant', 'Women Pant'), ('Women Shirt', 'Women Shirt'), ('Women Ladies Shoes', 'Women Ladies Shoes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='compatible_skin_tone',
            field=models.CharField(choices=[('Fair', 'Fair'), ('Medium', 'Medium'), ('Dark', 'Dark'), ('All', 'All')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='cultural_tag',
            field=models.CharField(choices=[('Eastern', 'Eastern'), ('Western', 'Western'), ('Casual', 'Casual'), ('Formal', 'Formal')], max_length=100),
        ),
    ]
